// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxtzh7LC7o9LIm--8YEObnPFNUT1qpPmo',
    appId: '1:523899752046:web:df79562be30ad45a83e07f',
    messagingSenderId: '523899752046',
    projectId: 'edulivekmo',
    authDomain: 'edulivekmo.firebaseapp.com',
    storageBucket: 'edulivekmo.appspot.com',
    measurementId: 'G-CR4Q9H73GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv_FaqEqfHvW3Ia4nd0g9UuOyD01hoDvw',
    appId: '1:523899752046:android:8461458445bbd50383e07f',
    messagingSenderId: '523899752046',
    projectId: 'edulivekmo',
    storageBucket: 'edulivekmo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSuq6q4gH9dYUzwPOa6ZLEdIdvkepRTxc',
    appId: '1:523899752046:ios:0014bd61ba9b050383e07f',
    messagingSenderId: '523899752046',
    projectId: 'edulivekmo',
    storageBucket: 'edulivekmo.appspot.com',
    iosBundleId: 'com.hariapp.edulive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSuq6q4gH9dYUzwPOa6ZLEdIdvkepRTxc',
    appId: '1:523899752046:ios:f2ee4da71deac0d783e07f',
    messagingSenderId: '523899752046',
    projectId: 'edulivekmo',
    storageBucket: 'edulivekmo.appspot.com',
    iosBundleId: 'com.hariapp.edulive.RunnerTests',
  );
}
